#!/bin/sh

cd ../pytest_tests

coverage run -m pytest --ignore=./stdio --ignore=./test_command_action.py --ignore=./test_command_handler_1.py --ignore=./test_command_handler_2.py -s -v
coverage run -m pytest ./test_command_action.py -s -v
coverage run -m pytest ./test_command_handler_1.py -s -v
coverage run -m pytest ./test_command_handler_2.py -s -v
coverage run -m pytest ./stdio

coverage report -m --include=../../tide/*
