#!/bin/sh

cd /work

RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${RED}Note to self: set password in ./tests/scripts/.pypirc before running${NC}"

cp tests/scripts/.pypirc /root

twine upload dist/* --verbose
